/**
 * SAMPLE INVENTORY — demo data only.
 * Imported exclusively by lib/inventory.ts (the repository layer).
 * Replaced by the live DMS/Homenet feed post-signing; nothing else
 * in the app may import this file.
 */
import type { VehicleRecord } from "@/lib/inventory";

export const sampleVehicles: VehicleRecord[] = [
  {
    id: "v-1001",
    slug: "2021-honda-cr-v-ex-l",
    stockNumber: "AMB-1001",
    year: 2021,
    make: "Honda",
    model: "CR-V",
    trim: "EX-L",
    price: 26900,
    mileage: 32410,
    bodyStyle: "SUV",
    exteriorColor: "Modern Steel Metallic",
    interiorColor: "Black Leather",
    drivetrain: "AWD",
    transmission: "CVT Automatic",
    fuel: "Gasoline",
    mpgCity: 27,
    mpgHighway: 32,
    features: ["One owner", "Heated leather seats", "Power tailgate", "Apple CarPlay / Android Auto", "Honda Sensing suite"],
    photos: ["/vehicles/2021-honda-cr-v-ex-l.webp"],
    status: "available",
    featured: true,
    highlight: "One owner, dealer-serviced since new.",
  },
  {
    id: "v-1002",
    slug: "2020-toyota-rav4-xle-awd",
    stockNumber: "AMB-1002",
    year: 2020,
    make: "Toyota",
    model: "RAV4",
    trim: "XLE",
    price: 24500,
    mileage: 41280,
    bodyStyle: "SUV",
    exteriorColor: "Magnetic Gray Metallic",
    interiorColor: "Black SofTex",
    drivetrain: "AWD",
    transmission: "8-Speed Automatic",
    fuel: "Gasoline",
    mpgCity: 27,
    mpgHighway: 33,
    features: ["Blind spot monitor", "Power moonroof", "Dual-zone climate", "Toyota Safety Sense 2.0"],
    photos: ["/vehicles/2020-toyota-rav4-xle-awd.webp"],
    status: "available",
    featured: true,
  },
  {
    id: "v-1003",
    slug: "2019-ford-f-150-xlt-supercrew",
    stockNumber: "AMB-1003",
    year: 2019,
    make: "Ford",
    model: "F-150",
    trim: "XLT SuperCrew 4x4",
    price: 29800,
    mileage: 58740,
    bodyStyle: "Truck",
    exteriorColor: "Oxford White",
    interiorColor: "Medium Earth Gray Cloth",
    drivetrain: "4WD",
    transmission: "10-Speed Automatic",
    fuel: "Gasoline",
    mpgCity: 19,
    mpgHighway: 24,
    features: ["2.7L EcoBoost V6", "Tow package", "Bedliner", "SYNC 3", "Remote start"],
    photos: ["/vehicles/2019-ford-f-150-xlt-supercrew.webp"],
    status: "available",
    featured: true,
    highlight: "Clean CARFAX, tow package installed.",
  },
  {
    id: "v-1004",
    slug: "2022-honda-civic-sport",
    stockNumber: "AMB-1004",
    year: 2022,
    make: "Honda",
    model: "Civic",
    trim: "Sport",
    price: 22400,
    mileage: 24960,
    bodyStyle: "Sedan",
    exteriorColor: "Rallye Red",
    interiorColor: "Black Cloth",
    drivetrain: "FWD",
    transmission: "CVT Automatic",
    fuel: "Gasoline",
    mpgCity: 30,
    mpgHighway: 37,
    features: ["One owner", "18-inch alloys", "Apple CarPlay / Android Auto", "Rear camera"],
    photos: ["/vehicles/2022-honda-civic-sport.webp"],
    status: "available",
    featured: true,
  },
  {
    id: "v-1005",
    slug: "2021-toyota-camry-se",
    stockNumber: "AMB-1005",
    year: 2021,
    make: "Toyota",
    model: "Camry",
    trim: "SE",
    price: 21900,
    mileage: 36150,
    bodyStyle: "Sedan",
    exteriorColor: "Celestial Silver Metallic",
    interiorColor: "Black SofTex",
    drivetrain: "FWD",
    transmission: "8-Speed Automatic",
    fuel: "Gasoline",
    mpgCity: 28,
    mpgHighway: 39,
    features: ["Sport-tuned suspension", "LED headlights", "Lane tracing assist"],
    photos: ["/vehicles/2021-toyota-camry-se.webp"],
    status: "available",
    featured: false,
  },
  {
    id: "v-1006",
    slug: "2020-chevrolet-equinox-lt-awd",
    stockNumber: "AMB-1006",
    year: 2020,
    make: "Chevrolet",
    model: "Equinox",
    trim: "LT",
    price: 18700,
    mileage: 47820,
    bodyStyle: "SUV",
    exteriorColor: "Summit White",
    interiorColor: "Jet Black Cloth",
    drivetrain: "AWD",
    transmission: "6-Speed Automatic",
    fuel: "Gasoline",
    mpgCity: 25,
    mpgHighway: 30,
    features: ["Heated front seats", "Remote start", "Teen Driver mode"],
    photos: ["/vehicles/2020-chevrolet-equinox-lt-awd.webp"],
    status: "available",
    featured: false,
  },
  {
    id: "v-1007",
    slug: "2018-subaru-outback-2-5i-premium",
    stockNumber: "AMB-1007",
    year: 2018,
    make: "Subaru",
    model: "Outback",
    trim: "2.5i Premium",
    price: 17500,
    mileage: 68430,
    bodyStyle: "Wagon",
    exteriorColor: "Wilderness Green Metallic",
    interiorColor: "Warm Ivory Cloth",
    drivetrain: "AWD",
    transmission: "CVT Automatic",
    fuel: "Gasoline",
    mpgCity: 25,
    mpgHighway: 32,
    features: ["EyeSight driver assist", "Roof rails", "All-weather package", "New tires"],
    photos: ["/vehicles/2018-subaru-outback-2-5i-premium.webp"],
    status: "available",
    featured: false,
  },
  {
    id: "v-1008",
    slug: "2021-ford-escape-se-awd",
    stockNumber: "AMB-1008",
    year: 2021,
    make: "Ford",
    model: "Escape",
    trim: "SE",
    price: 19900,
    mileage: 39610,
    bodyStyle: "SUV",
    exteriorColor: "Velocity Blue",
    interiorColor: "Ebony Cloth",
    drivetrain: "AWD",
    transmission: "8-Speed Automatic",
    fuel: "Gasoline",
    mpgCity: 26,
    mpgHighway: 31,
    features: ["Co-Pilot360", "SYNC 3", "Dual-zone climate", "Keyless entry"],
    photos: ["/vehicles/2021-ford-escape-se-awd.webp"],
    status: "pending",
    featured: false,
  },
];
